apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-sovkombank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app-sovkombank
  template:
    metadata:
      labels:
        app: nginx-app-sovkombank
    spec:
      #hostAliases:
      #- ip: "172.64.195.16"
        #hostnames:
        #- "ifconfig.io"
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: sovkombank-configmap

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sovkombank-configmap
data:
  nginx.conf: |
    events {}
    http {
        upstream ifconfig {
            server ifconfig.io:443;
       }

    server {
        listen      80;
        listen      443;
        #return 301 https://ifconfig$request_uri;
        #listen 443;
        location / {
            proxy_set_header Host ifconfig.io;
            proxy_pass  https://ifconfig;
            proxy_ssl_server_name on;
            proxy_ssl_name ifconfig.io;
            #proxy_set_header X-Real-IP 5.35.4.28;
            #proxy_set_header X-Forwarded-For 5.35.4.28;

            }
        }
    }

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-sovkombank
spec:
  tls:
  - hosts:
      - test.ifconfig.io
  ingressClassName: nginx
  rules:
    - host: test.ifconfig.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service-sovkombank
                port:
                  number: 443

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-sovkombank
spec:
  selector:
    app: nginx-app-sovkombank
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
