apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  nginx.conf: |
    events {}
    http {
      server {
        location / {
          proxy_pass https://ifconfig.io;
        }
      }
    }
