apiVersion: v1
kind: ConfigMap
metadata:
  name: sovkombank-configmap
data:
  nginx.conf: |
    events {}
    http {
        upstream ifconfig {
            server ifconfig.io:443;
       }

    server {
        listen      80;
        listen      443;
        #return 301 https://ifconfig$request_uri;
        #listen 443;
        location / {
            proxy_set_header Host ifconfig.io;
            proxy_pass  https://ifconfig;
            proxy_ssl_server_name on;
            proxy_ssl_name ifconfig.io;
            #proxy_set_header X-Real-IP 5.35.4.28;
            #proxy_set_header X-Forwarded-For 5.35.4.28;

            }
        }
    }
