apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-sovkombank
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-app-sovkombank
  template:
    metadata:
      labels:
        app: nginx-app-sovkombank
    spec:
      #hostAliases:
      #- ip: "172.64.195.16"
        #hostnames:
        #- "ifconfig.io"
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-conf
        configMap:
          name: sovkombank-configmap
